# Generated by Django 4.1.4 on 2023-01-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_kodi', models.CharField(max_length=60)),
                ('fan_nomi', models.CharField(max_length=250)),
                ('talaba', models.CharField(max_length=200)),
                ('telefon_raqam', models.CharField(max_length=40)),
                ('savollar_soni', models.IntegerField()),
                ('togri_javoblar', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Natija ',
                'verbose_name_plural': 'Natijalar ',
            },
        ),
    ]
