# Generated by Django 4.1.4 on 2023-01-02 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0002_alter_user_options_alter_user_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('DIRECTOR', 'director'), ('MANAGER', 'manager'), ('TEACHER', 'teacher')], max_length=15, null=True),
        ),
    ]
